function X = set_design_matrix(bval, bvec, model, scalingFactor)
    N = length(bval);
    try
        switch model
            case 'DT'
                X = zeros( N, 7);
                for i = 1 : N
                    b = bval( i );
                    g1 = bvec( i, 1 );
                    g2 = bvec( i, 2 );
                    g3 = bvec( i, 3 );    
                    b_DT =  b .* [ ...
                       g1^2, ...
                       2 * g1 * g2, ...
                       2 * g1 * g3, ...
                       g2^2, ...
                       2 * g2 * g3, ...
                       g3^2];
                   X( i, : ) = [ 1, -b_DT ];
                end
                X(:, 2:7) = X(:, 2:7)./scalingFactor;
            case 'KT'
                X = zeros( N, 22);
                for i = 1 : N
                    b = bval( i );
                    g1 = bvec( i, 1 );
                    g2 = bvec( i, 2 );
                    g3 = bvec( i, 3 );    
                    b_DT =  b .* [ ...
                        g1^2, ...
                        2 * g1 * g2, ...
                        2 * g1 * g3, ...
                        g2^2, ...
                        2 * g2 * g3, ...
                        g3^2];
                    b_KT = b^2 / 54 .* [...
                        g1^4, ...
                        g2^4, ...
                        g3^4, ...
                        4 * g1^3 * g2, ...
                        4 * g1^3 * g3, ...
                        4 * g2^3 * g1, ...
                        4 * g2^3 * g3, ...
                        4 * g3^3 * g1, ...
                        4 * g3^3 * g2, ...
                        6 * g1^2 * g2^2, ...
                        6 * g1^2 * g3^2, ...
                        6 * g2^2 * g3^2, ...
                        12 * g1^2 * g2 * g3, ...
                        12 * g2^2 * g1 * g3, ...
                        12 * g3^2 * g1 * g2 ];
                    X( i, : ) = [ 1, -b_DT, b_KT ] ;                      
                end
                X(:, 2:7) = X(:, 2:7)./scalingFactor;
                X(:, 8:end) = X(:, 8:end)./(scalingFactor^2);
        end
    catch ME
        throw(ME);
    end

end